dependencies {

  implementation project(':formod-rc')
 
  implementation project(':b-ta')
  implementation project(':b-ta-ui')
 
 
  // openflexo dep
  implementation flexoFoundation()
  implementation flexoUi()
  implementation fmlRtTechnologyAdapterUi()
  implementation flexoDocumentation()
  implementation flexoDocumentationUi()
  implementation flexoUtils()
  implementation flexoGraphicUtils()
  implementation diagramConnector()
  implementation diagramConnectorUi()
  implementation docxConnector()
  implementation docxConnectorUi()
  implementation excelConnector()
  implementation excelConnectorUi()
  implementation ginaConnector()
  implementation ginaConnectorUi()
  implementation owlConnector()
  implementation owlConnectorUi()
  
  runtimeOnly flexoGraphicUtils()
  
  
  // external dep
  
  // testing dep
  testImplementation testUtils()
  testImplementation ginaTest()
  testImplementation ginaSwingEditorTest()
  testImplementation flexoFoundationTest()
  testImplementation flexoUiTest()
  testRuntimeOnly flexoTestResources()
   
}
