dependencies {
  implementation project(":b-ta")
  // Use following to test b-ta using jar artefact
  //implementation group: 'org.openflexo', name: 'b-ta', version: '2.99-SNAPSHOT'
  implementation flexoFoundation()

  implementation testUtils()
  implementation flexoFoundationTest()

  // Test resource center
  testRuntimeOnly project(':b-ta-test-rc')
}
